### ISSUE TITLE
can't save

### ISSUE THREAD

**Issue by HawkenKing** [dacap/export-aseprite-file#6]
Maybe this is a MACOSX permissions issue, I gave the script full access however I get the following message when running it:
<img width="568" alt="Screenshot 2024-08-20 at 20 12 41" src="https://github.com/user-attachments/assets/14d773f3-900c-4c7b-acce-e33bea1632f0">

**Comment by dacap** [comment]
Hi @HawkenKing! It looks like the script wants to write into the /map folder located in the root file system, is that right? Should not be the output folder inside your $HOME?

**Comment by HawkenKing** [comment]
hi @dacap I installed the latest version to see if that might help (1.3.7) I get a different message when running the script:

> Aseprite can't save "/map" file ("")
> ~/export-tilemap/export.lua:21: attempt to index a nil value (local 'file')

**Comment by HawkenKing** [comment]
When I try via terminal, via this command line, I don't get a maps folder generated, no message is printed in terminal:

`/Applications/Aseprite.app/Contents/MacOS/aseprite -b /computer/Desktop/map.aseprite -script /computer/Library/Application Support/Aseprite/scripts/export-tilemap/export.lua`

**Comment by justgook** [comment]
i crated pull request #7  - that should fix it - it will create folder same name as aseprite file next to it. it works on MacOS - i do not have any other OS - would be nice to check if it not works on other OSes

**Comment by dacap** [comment]
Thanks @justgook, I've just tested your patch on Linux. I can see the difference: with the `main`  version of the script, the default output path will be the current directory, and with your patch it will be the same path of the sprite. I'll merge it right now.
